export interface CasinoListItem {
  id: string;
  name: string;
  slug: string;
  enabled: boolean;
}

export const casinoListConfig: CasinoListItem[] = [
  {
    id: 'lucky-7-a',
    name: 'Lucky 7 - A',
    slug: 'lucky7',
    enabled: true,
  },
  {
    id: 'lucky-7-b',
    name: 'Lucky 7 - B',
    slug: 'lucky7B',
    enabled: true,
  },
  {
    id: '20-20-teenpatti',
    name: '20-20 Teenpatti',
    slug: 'teen20',
    enabled: false,
  },
  {
    id: '1-day-teenpatti',
    name: '1 Day Teenpatti',
    slug: 'Tp1Day',
    enabled: false,
  },
  {
    id: 'open-teenpatti',
    name: 'Open Teenpatti',
    slug: 'opentp',
    enabled: false,
  },
  {
    id: 'test-teenpatti',
    name: 'Test Teenpatti',
    slug: 'testtp',
    enabled: false,
  },
  {
    id: 'teen-patti-2020',
    name: 'Teen Patti 2020',
    slug: 'Teen Patti 2020',
    enabled: false,
  },
  {
    id: 'roulette-1',
    name: 'Roulette',
    slug: 'Roulette',
    enabled: false,
  },
  {
    id: 'amar-akbar-anthony',
    name: 'Amar Akbar Anthony',
    slug: 'AAA',
    enabled: false,
  },
  {
    id: 'roulette-2',
    name: 'Roulette',
    slug: 'Roulette',
    enabled: false,
  },
  {
    id: 'roulette-3',
    name: 'Roulette',
    slug: 'Roulette',
    enabled: false,
  },
  {
    id: 'bollywood-table',
    name: 'Bollywood Table',
    slug: 'ddb',
    enabled: false,
  },
  {
    id: '20-20-dragon-tiger-2',
    name: '20-20 Dragon Tiger 2',
    slug: 'dt20b',
    enabled: false,
  },
  {
    id: '20-20-dragon-tiger',
    name: '20-20 Dragon Tiger',
    slug: 'dt20',
    enabled: false,
  },
  {
    id: '1-day-dragon-tiger',
    name: '1 Day Dragon Tiger',
    slug: 'dragontiger1Day',
    enabled: false,
  },
  {
    id: '20-20-dtl',
    name: '20-20 DTL',
    slug: 'dtl20',
    enabled: false,
  },
  {
    id: 'baccarat',
    name: 'Baccarat',
    slug: 'baccarat',
    enabled: false,
  },
  {
    id: 'sicbo',
    name: 'Sicbo',
    slug: 'MPlay',
    enabled: false,
  },
  {
    id: 'the-trap',
    name: 'The Trap',
    slug: 'KAGaming',
    enabled: false,
  },
  {
    id: 'lucky-blue',
    name: 'Lucky Blue',
    slug: 'BGaming',
    enabled: false,
  },
  {
    id: '1-card-meter',
    name: '1 Card Meter',
    slug: '1-card-meter',
    enabled: false,
  },
  {
    id: 'dus-ka-dum',
    name: 'Dus ka Dum',
    slug: 'dus-ka-dum',
    enabled: true,
  },
  {
    id: 'baccarat-2',
    name: 'Baccarat 2',
    slug: 'baccarat2',
    enabled: false,
  },
  {
    id: '20-20-poker',
    name: '20-20 Poker',
    slug: 'onedaypoker20',
    enabled: false,
  },
  {
    id: '1-day-poker',
    name: '1 Day Poker',
    slug: 'onedaypoker',
    enabled: false,
  },
  {
    id: '6-player-poker',
    name: '6 Player Poker',
    slug: 'poker6player',
    enabled: false,
  },
  {
    id: '32-cards-a',
    name: '32 Cards A',
    slug: 'card32',
    enabled: false,
  },
  {
    id: '32-cards-b',
    name: '32 Cards B',
    slug: 'card32b',
    enabled: false,
  },
  {
    id: 'casino-meter',
    name: 'Casino Meter',
    slug: 'cmeter2020',
    enabled: false,
  },
  {
    id: '20-20-cricket-match',
    name: '20-20 Cricket Match',
    slug: 'cricket2020',
    enabled: false,
  },
  {
    id: '3-cards-judgement',
    name: '3 Cards Judgement',
    slug: 'Cards3J',
    enabled: false,
  },
  {
    id: 'super-over',
    name: 'Super Over',
    slug: 'Superover',
    enabled: false,
  },
  {
    id: '5five-cricket',
    name: '5Five Cricket',
    slug: 'fivewicket',
    enabled: false,
  },
  {
    id: 'race-20-20',
    name: 'Race 20-20',
    slug: 'race2020',
    enabled: false,
  },
  {
    id: 'casino-war',
    name: 'Casino War',
    slug: 'warcasino',
    enabled: false,
  },
  {
    id: 'casino-queen',
    name: 'Casino Queen',
    slug: 'queen',
    enabled: false,
  },
  {
    id: 'andar-bahar',
    name: 'Andar Bahar',
    slug: 'Andarbhar',
    enabled: false,
  },
  {
    id: 'andar-bahar-2',
    name: 'Andar Bahar 2',
    slug: 'Andarbhar2',
    enabled: false,
  },
  {
    id: 'instant-worli',
    name: 'Instant Worli',
    slug: 'worliinstant',
    enabled: false,
  },
  {
    id: 'instant-teenpatti-3',
    name: 'Instant Teenpatti 3.0',
    slug: 'InstantTeenpatti3.0',
    enabled: true,
  },
  {
    id: 'ball-by-ball',
    name: 'Ball by Ball',
    slug: 'Ball-by-Ball',
    enabled: true,
  },
  {
    id: 'lucky-15',
    name: 'Lucky 15',
    slug: 'Lucky-15',
    enabled: true,
  },
  {
    id: 'goal',
    name: 'Goal',
    slug: 'Goal',
    enabled: true,
  },
  {
    id: 'mini-superover',
    name: 'Mini Superover',
    slug: 'Mini-Superover',
    enabled: true,
  },
  {
    id: 'bollywood-casino-2',
    name: 'Bollywood Casino 2',
    slug: 'Bollywood-Casino-2',
    enabled: true,
  },
  {
    id: '2-cards-teenpatti',
    name: '2 Cards Teenpatti',
    slug: '2-Cards-Teenpatti',
    enabled: true,
  },
  {
    id: 'sic-bo2',
    name: 'Sic Bo2',
    slug: 'Sic-o2',
    enabled: true,
  },
  {
    id: '1-card-one-day',
    name: '1 CARD ONE-DAY',
    slug: '1-CARD-ONE-DAY',
    enabled: true,
  },
  {
    id: '29-card-baccarat',
    name: '29Card Baccarat',
    slug: '29Card-Baccarat',
    enabled: true,
  },
  {
    id: 'race-to-2nd',
    name: 'Race to 2nd',
    slug: 'Race-to-2nd',
    enabled: true,
  },
];
