export interface LiveCasinoGame {
  id: string;
  label: string;
  slug: string;
  path: string;
}

export const liveCasinoGames: LiveCasinoGame[] = [
  {
    id: 'lucky-7-a',
    label: 'Lucky 7 - A',
    slug: 'lucky-7-a',
    path: '/admin/live-casino/lucky-7-a',
  },
  {
    id: 'lucky-7-b',
    label: 'Lucky 7 - B',
    slug: 'lucky-7-b',
    path: '/admin/live-casino/lucky-7-b',
  },
  {
    id: '20-20-teenpatti',
    label: '20-20 Teenpatti',
    slug: '20-20-teenpatti',
    path: '/admin/live-casino/20-20-teenpatti',
  },
  {
    id: '1-day-teenpatti',
    label: '1 Day Teenpatti',
    slug: '1-day-teenpatti',
    path: '/admin/live-casino/1-day-teenpatti',
  },
  {
    id: 'open-teenpatti',
    label: 'Open Teenpatti',
    slug: 'open-teenpatti',
    path: '/admin/live-casino/open-teenpatti',
  },
  {
    id: 'test-teenpatti',
    label: 'Test Teenpatti',
    slug: 'test-teenpatti',
    path: '/admin/live-casino/test-teenpatti',
  },
  {
    id: 'teen-patti-2020',
    label: 'Teen Patti 2020',
    slug: 'teen-patti-2020',
    path: '/admin/live-casino/teen-patti-2020',
  },
  {
    id: 'roulette-1',
    label: 'Roulette',
    slug: 'roulette',
    path: '/admin/live-casino/roulette',
  },
  {
    id: 'amar-akbar-anthony',
    label: 'Amar Akbar Anthony',
    slug: 'amar-akbar-anthony',
    path: '/admin/live-casino/amar-akbar-anthony',
  },
  {
    id: 'roulette-2',
    label: 'Roulette',
    slug: 'roulette-2',
    path: '/admin/live-casino/roulette-2',
  },
  {
    id: 'bollywood-table',
    label: 'Bollywood Table',
    slug: 'bollywood-table',
    path: '/admin/live-casino/bollywood-table',
  },
  {
    id: '20-20-dragon-tiger-2',
    label: '20-20 Dragon Tiger 2',
    slug: '20-20-dragon-tiger-2',
    path: '/admin/live-casino/20-20-dragon-tiger-2',
  },
  {
    id: '20-20-dragon-tiger',
    label: '20-20 Dragon Tiger',
    slug: '20-20-dragon-tiger',
    path: '/admin/live-casino/20-20-dragon-tiger',
  },
  {
    id: '1-day-dragon-tiger',
    label: '1 Day Dragon Tiger',
    slug: '1-day-dragon-tiger',
    path: '/admin/live-casino/1-day-dragon-tiger',
  },
  {
    id: '20-20-dtl',
    label: '20-20 DTL',
    slug: '20-20-dtl',
    path: '/admin/live-casino/20-20-dtl',
  },
  {
    id: 'baccarat',
    label: 'Baccarat',
    slug: 'baccarat',
    path: '/admin/live-casino/baccarat',
  },
  {
    id: 'sicbo',
    label: 'Sicbo',
    slug: 'sicbo',
    path: '/admin/live-casino/sicbo',
  },
  {
    id: 'the-trap',
    label: 'The Trap',
    slug: 'the-trap',
    path: '/admin/live-casino/the-trap',
  },
  {
    id: 'lucky-blue',
    label: 'Lucky Blue',
    slug: 'lucky-blue',
    path: '/admin/live-casino/lucky-blue',
  },
  {
    id: '1-card-meter',
    label: '1 Card Meter',
    slug: '1-card-meter',
    path: '/admin/live-casino/1-card-meter',
  },
  {
    id: 'dus-ka-dum',
    label: 'Dus Ka Dum',
    slug: 'dus-ka-dum',
    path: '/admin/live-casino/dus-ka-dum',
  },
  {
    id: 'baccarat-2',
    label: 'Baccarat 2',
    slug: 'baccarat-2',
    path: '/admin/live-casino/baccarat-2',
  },
  {
    id: '20-20-poker',
    label: '20-20 Poker',
    slug: '20-20-poker',
    path: '/admin/live-casino/20-20-poker',
  },
  {
    id: '1-day-poker',
    label: '1 Day Poker',
    slug: '1-day-poker',
    path: '/admin/live-casino/1-day-poker',
  },
  {
    id: '6-player-poker',
    label: '6 Player Poker',
    slug: '6-player-poker',
    path: '/admin/live-casino/6-player-poker',
  },
  {
    id: '32-cards-a',
    label: '32 Cards A',
    slug: '32-cards-a',
    path: '/admin/live-casino/32-cards-a',
  },
  {
    id: '32-cards-b',
    label: '32 Cards B',
    slug: '32-cards-b',
    path: '/admin/live-casino/32-cards-b',
  },
  {
    id: 'casino-meter',
    label: 'Casino Meter',
    slug: 'casino-meter',
    path: '/admin/live-casino/casino-meter',
  },
  {
    id: '20-20-cricket-match',
    label: '20-20 Cricket Match',
    slug: '20-20-cricket-match',
    path: '/admin/live-casino/20-20-cricket-match',
  },
  {
    id: '3-cards-judgement',
    label: '3 Cards Judgement',
    slug: '3-cards-judgement',
    path: '/admin/live-casino/3-cards-judgement',
  },
  {
    id: 'super-over',
    label: 'Super Over',
    slug: 'super-over',
    path: '/admin/live-casino/super-over',
  },
  {
    id: '5five-cricket',
    label: '5Five Cricket',
    slug: '5five-cricket',
    path: '/admin/live-casino/5five-cricket',
  },
  {
    id: 'race-20-20',
    label: 'Race 20-20',
    slug: 'race-20-20',
    path: '/admin/live-casino/race-20-20',
  },
  {
    id: 'casino-war',
    label: 'Casino War',
    slug: 'casino-war',
    path: '/admin/live-casino/casino-war',
  },
  {
    id: 'casino-queen',
    label: 'Casino Queen',
    slug: 'casino-queen',
    path: '/admin/live-casino/casino-queen',
  },
  {
    id: 'andar-bahar',
    label: 'Andar Bahar',
    slug: 'andar-bahar',
    path: '/admin/live-casino/andar-bahar',
  },
  {
    id: 'andar-bahar-2',
    label: 'Andar Bahar 2',
    slug: 'andar-bahar-2',
    path: '/admin/live-casino/andar-bahar-2',
  },
  {
    id: 'instant-worli',
    label: 'Instant Worli',
    slug: 'instant-worli',
    path: '/admin/live-casino/instant-worli',
  },
  {
    id: 'instant-teenpatti-3-0',
    label: 'Instant Teenpatti 3.0',
    slug: 'instant-teenpatti-3-0',
    path: '/admin/live-casino/instant-teenpatti-3-0',
  },
  {
    id: 'ball-by-ball',
    label: 'Ball By Ball',
    slug: 'ball-by-ball',
    path: '/admin/live-casino/ball-by-ball',
  },
  {
    id: 'lucky-15',
    label: 'Lucky 15',
    slug: 'lucky-15',
    path: '/admin/live-casino/lucky-15',
  },
  {
    id: 'goal',
    label: 'Goal',
    slug: 'goal',
    path: '/admin/live-casino/goal',
  },
  {
    id: 'mini-superover',
    label: 'Mini Superover',
    slug: 'mini-superover',
    path: '/admin/live-casino/mini-superover',
  },
  {
    id: 'bollywood-casino-2',
    label: 'Bollywood Casino 2',
    slug: 'bollywood-casino-2',
    path: '/admin/live-casino/bollywood-casino-2',
  },
  {
    id: '2-cards-teenpatti',
    label: '2 Cards Teenpatti',
    slug: '2-cards-teenpatti',
    path: '/admin/live-casino/2-cards-teenpatti',
  },
  {
    id: 'sic-bo2',
    label: 'Sic Bo2',
    slug: 'sic-bo2',
    path: '/admin/live-casino/sic-bo2',
  },
  {
    id: '1-card-one-day',
    label: '1 CARD ONE-DAY',
    slug: '1-card-one-day',
    path: '/admin/live-casino/1-card-one-day',
  },
  {
    id: '29card-baccarat',
    label: '29Card Baccarat',
    slug: '29card-baccarat',
    path: '/admin/live-casino/29card-baccarat',
  },
  {
    id: 'race-to-2nd',
    label: 'Race To 2nd',
    slug: 'race-to-2nd',
    path: '/admin/live-casino/race-to-2nd',
  },
];
